// Generated by CoffeeScript 2.3.2
(function() {
  var family, name;

  name = function(name, age, color) {
    return `My name is ${name}, I am ${age} years old. My favorite color is ${color} `;
  };

  family = {
    mother: {
      name: 'Someone',
      age: '32'
    },
    father: {
      name: 'mood'
    }
  };

}).call(this);
